---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.16.4
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---



```{python}
# Don't change this cell; just run it.
import numpy as np  # The array library.
```

This notebook does not have OKpy tests; please check your answers against the
"visual check" hints after each question.

All the cells below have errors in syntax or in logic. A syntax error happens
when the code does not correspond to Python's rules; Python generates an error
with some information about which bit of the code caused the problem.  A logic
error is where the code does run, but does not do what it was intended to do.
Run the cells to see the error, and then fix them to work correctly.

```{python tags=c("raises-exception")}
#- Print the numbers 0 through 2
for my_var in np.arange(3)
    print(my_var)
```

Visual check: you should see:

```
0
1
2
```

```{python tags=c("raises-exception")}
#- Add up all the numbers from 3 through 10
total = 0
for i in np.arange(3, 11):
total = total + i
print(total)
```

Visual check - you should see 52.

```{python tags=c("raises-exception")}
#- Print all the numbers from 5 through 9
for p in 56789:
    print(p)
```

You should see the numbers 5, 6, 7, 8, 9 printed, each on one line.

```{python tags=c("raises-exception")}
#- Add all numbers from 3 down to -2, inclusive
total = 0
for i = np.arange(3, -4, -1):
    total = total + i
print(total)
```

Visual check - you should have printed 3.

```{python tags=c("raises-exception")}
#- Add up the squares of all the even numbers from -2 through 20
total = 0
for v in np.arange(-2, 21):
    squared = v ** 2
     total = total + squared
print(total)
```

Visual check - you should see 1544.

```{python}
#- Add all the odd numbers from 11 through 21
total = 0
for value in np.arange(11, 21):
    total = total + value
print(total)
```

Visual check - you should see 96.  If you don't, check that the first number
from your `arange` is 11, and the last is 22.

```{python}
#- Print all the numbers starting from 100, and subtracting 7
#- up to the last positive number.  The first three
#- numbers you will print will be 100, 93, 86
for i in np.arange(100, 7, 7):
    print(i)
```

Visual check - you should see the numbers 100, 93, ..., 9, 2 printed, each on
one line.

```{python}
#- Add every third number in the inclusive range 1 through 19.
#- The first two numbers to add will therefore be 1, 4 and the last
#- will be 19.
total = 0
for i in np.arange(1, 21):
    total = total + 1
print(total)
```

Visual check - the result should be 70.
